MODEL:
  NUM_CLASSES: 3
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("customer_train", )
  TEST: ("customer_val", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 8
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_customer'